# Generated by Django 6.1.1 on 2026-10-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_wishlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
